channels/urls.py
from django.conf.urls import url
from . import views

app_name = 'channels'
urlpatterns = [
    # ex: /channels/
    url(r'^$', views.ChannelListView.as_view(), name='channel_list'),
    # ex: /channels/5/
    url(r'^(?P<pk>[0-9]+)/$', views.ChannelDetailView.as_view(), name='channel_detail'),
]

sms/urls.py
from django.conf.urls import url
from . import views

app_name = 'sms'
urlpatterns = [
    # ex: /sms/
    url(r'^$', views.sms),
]

tada/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/channels/', permanent=False), name='index'),
    url(r'^channels/', include('channels.urls')),
    url(r'^sms/', include('sms.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', auth_views.login, {'template_name': 'channels/login.html'}),
    url(r'^accounts/logout/$', auth_views.logout_then_login, name='logout'),
]

channels/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import User

@python_2_unicode_compatible
class Channel(models.Model):
    users = models.ManyToManyField(User)
    name = models.CharField(max_length=200)
    creation_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name
    
@python_2_unicode_compatible
class Post(models.Model):
    channel = models.ForeignKey(Channel, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post_text = models.CharField(max_length=200)
    creation_date = models.DateTimeField(auto_now_add=True)  
    
    def __str__(self):
        return self.post_text

sms/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

channels/forms.py
from django import forms

class ChannelPostForm(forms.Form):
    post = forms.CharField(max_length=200, label='Post something')

channels/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.core.urlresolvers import reverse
from django.contrib.auth.mixins import LoginRequiredMixin, AccessMixin
from django.http import HttpResponseRedirect

from .models import Channel, Post
from .forms import ChannelPostForm

class ChannelHasUserMixin(AccessMixin):
    """
    Mixin that verifies a channel has the current user.
    """
    
    raise_exception = True
    permission_denied_message = "You don't have access to this channel."
          
    def channel_has_user(self, channel):
        return channel.users.filter(id=self.request.user.id).exists()
    
    def get_object(self):
        retrieved_object = super(ChannelHasUserMixin, self).get_object()
        if self.channel_has_user(retrieved_object):
            return retrieved_object
        else:
            self.handle_no_permission()

class ChannelListView(LoginRequiredMixin, generic.ListView):
    context_object_name = 'channel_list'
    template_name = 'channels/channel_list.html'
    
    def get_queryset(self):
        return Channel.objects.filter(users=self.request.user).order_by('name')
         
class ChannelDetailView(LoginRequiredMixin, ChannelHasUserMixin, generic.DetailView):
    channel_post_form = ChannelPostForm
    model = Channel
    template_name = 'channels/channel_detail.html'
    
    def get_context_data(self, **kwargs):
        context = super(ChannelDetailView, self).get_context_data(**kwargs)
        context['post_list'] = self.object.post_set.order_by('-creation_date')
        context['channel_post_form'] = self.channel_post_form
        return context
           
    def post(self, request, *args, **kwargs):
        """
        Process text posted from the channel detail page.
        """
        self.object = self.get_object()
        form = self.channel_post_form(request.POST)
        if form.is_valid():
            channel_post = Post.objects.create(
                user=self.request.user,
                channel = self.object,
                post_text = form.cleaned_data['post']
            )
            channel_post.save()
        return redirect('channels:channel_detail', pk=self.object.id)

sms/views.py
from django.shortcuts import render
from django_twilio.decorators import twilio_view
from twilio.twiml import Response
 
@twilio_view
def sms(request):
    r = Response()
    r.message('Hello from your Django app!')
    return r

channels/templates/channels/base.html
{% extends 'bootstrap3/bootstrap3.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_title %}Tada{% endblock %}

{% block bootstrap3_extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'channels/style.css' %}">
{% endblock %}

{% block bootstrap3_content %}
<div class="container">
	
	<!-- Static navbar -->
	      <nav class="navbar navbar-default">
	        <div class="container-fluid">
	          <div class="navbar-header">
	            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	              <span class="sr-only">Toggle navigation</span>
	              <span class="icon-bar"></span>
	              <span class="icon-bar"></span>
	              <span class="icon-bar"></span>
	            </button>
	            <a class="navbar-brand" href="{% url 'channels:channel_list' %}">Tada</a>
	          </div>
	          <div id="navbar" class="navbar-collapse collapse">
	            <ul class="nav navbar-nav navbar-right">
	              <li><a href="{% url 'logout' %}">Logout</a></li>
	            </ul>
	          </div><!--/.nav-collapse -->
	        </div><!--/.container-fluid -->
	      </nav>


    <h1>{% block title %}(no title){% endblock %}</h1>

    {% bootstrap_messages %}

    {% block content %}(no content){% endblock %}
</div>

{% endblock %}

channels/templates/channels/channel_detail.html
{% extends 'channels/base.html' %}
{% load bootstrap3 %}

{% block title %}
	<h2>{{ user.username}} : {{ channel.name }}</h2>
{% endblock %}

{% block content %}
	<div class="row post_form">
		<form method="post" class="col-sm-12">
			{% csrf_token %}
			{% bootstrap_form channel_post_form %}
			{% bootstrap_button "post" button_type="submit" button_class="btn-primary pull-right" %}
		</form>
	</div>
	{% for post in post_list %}
		<div class="row post">
			<div class="col-sm-12">
				<div class="row">
					<div class="col-sm-6">
						<h4>{{ post.user.username }}</h3>
					</div>
					<div class="col-sm-6 text-right">
						{{ post.creation_date|date:"D d M Y" }} 
						{{ post.creation_date|time:"H:i" }}
					</div>
				</div>
				<div class="row">
					<div class="col-sm-12">{{ post.post_text }}</div>
				</div>
			</div>
		</div>
	{% endfor %}
{% endblock %}

channels/templates/channels/channel_list.html
{% extends 'channels/base.html' %}
{% load bootstrap3 %}

{% block title %}
<h2>Channels for {{ user.username }} </h2>
{% endblock %}

{% block content %}
	{% if channel_list %}
		<ul class="list-unstyled channel-list">
		{% for channel in channel_list %}
			<li><a href="{% url 'channels:channel_detail' channel.id %}">{{ channel.name }}</a></li>
		{% endfor %}
		</ul>
	{% else %}
		<p>No channels available.</p>
	{% endif %}
{% endblock %}

channels/templates/channels/login.html
{% extends 'bootstrap3/bootstrap3.html' %}
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_extra_head %}
<style>
body {
  padding-top: 40px;
  padding-bottom: 40px;
  background-color: #eee;
}

.form-signin {
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
}
.form-signin .form-signin-heading,
.form-signin .checkbox {
  margin-bottom: 10px;
}
.form-signin .checkbox {
  font-weight: normal;
}
.form-signin .form-control {
  position: relative;
  height: auto;
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
  padding: 10px;
  font-size: 16px;
}
.form-signin .form-control:focus {
  z-index: 2;
}
.form-signin input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
</style>
{% endblock %}

{% block bootstrap3_content %}
	<div class="container">
		
		<form class="form-signin" method="post" action="/accounts/login/">
			{% if next %}
			    {% if user.is_authenticated %}
			    <p>Your account doesn't have access to this page. To proceed,
			    please login with an account that has access.</p>
			    {% else %}
			    <p>Please login to see this page.</p>
			    {% endif %}
			{% endif %}
			<h2 class="form-signin-heading">Please sign in</h2>
			{% csrf_token %}
			{% bootstrap_form form %}
			{% bootstrap_button "login" button_type="submit" button_class="btn-lg btn-primary btn-block" %}
			<input type="hidden" name="next" value="{{ next }}" />
		</form>
	</div> <!-- container -->
{% endblock %}